# Generated by Django 4.0.6 on 2022-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('payer', 'Payer'), ('admin', 'Admin'), ('superAdmin', 'SuperAdmin')], default='student', max_length=50),
        ),
    ]
