# Generated by Django 4.0.6 on 2022-07-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_payerprofile_user_alter_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flakon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
