# Generated by Django 4.0.6 on 2022-07-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_flakon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flakon',
        ),
    ]
