# Generated by Django 4.0.6 on 2022-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_study_alter_user_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid_by_parents',
            field=models.BooleanField(default=False),
        ),
    ]
