# Generated by Django 4.0.6 on 2022-08-18 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_user_payer_user_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
