# Generated by Django 4.0.6 on 2022-07-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
