# Generated by Django 4.0.6 on 2022-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_group_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='even',
            field=models.BooleanField(default=True),
        ),
    ]
