# Generated by Django 4.0.6 on 2022-07-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_groupmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.AddField(
            model_name='groupmonth',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='groupmonth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupmonth_lessons', to='main.groupmonth'),
        ),
    ]
