# Generated by Django 4.0.6 on 2022-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_lesson_group_groupmonth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
