# Generated by Django 4.0.6 on 2022-07-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lesson_theme'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('date', 'groupmonth')},
        ),
    ]
