# Generated by Django 4.0.6 on 2022-07-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmonth',
            name='month',
            field=models.DateField(auto_now_add=True),
        ),
    ]
