# Generated by Django 4.0.6 on 2022-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_groupstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
