# Generated by Django 4.0.6 on 2022-07-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_groupstudent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
