# Generated by Django 4.0.6 on 2022-07-25 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_alter_groupstudent_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupstudent',
            unique_together={('created', 'student', 'group')},
        ),
    ]
