# Generated by Django 4.0.6 on 2022-07-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_groupstudent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonstudent',
            unique_together=set(),
        ),
    ]
