# Generated by Django 4.0.6 on 2022-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_lessonstudent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstudent',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
