# Generated by Django 4.0.6 on 2022-07-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_lessonstudent_sms_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstudent',
            name='homework_done',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lessonstudent',
            name='is_available',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
